LINK_GEO = "https://293ll8nkfa.execute-api.us-east-1.amazonaws.com/develop/api/v1/geografia"
LINK_CATE = "https://293ll8nkfa.execute-api.us-east-1.amazonaws.com/develop/api/v1/categorizacion?comuna="
LINK_MINIMO = "https://293ll8nkfa.execute-api.us-east-1.amazonaws.com/develop/api/v1/carro/calculo/minimo"
LINK_PROMEDIO = "https://293ll8nkfa.execute-api.us-east-1.amazonaws.com/develop/api/v1/carro/calculo/promedio"
LINK_DISPO = "https://293ll8nkfa.execute-api.us-east-1.amazonaws.com/develop/api/v1/carro/disponibilidad"
LINK_RANGOS = "https://293ll8nkfa.execute-api.us-east-1.amazonaws.com/develop/api/v1/subcategorias/{}/rangos"